services:
  - type: web
    name: rrs-system
    env: python
    pythonVersion: 3.13
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT}"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "Pz3H|8K8M^v#nQ3z}Ym;1neWyfcSqssp+$1f;f5GMBl^]dLMvV"
      - key: ALLOWED_HOSTS
        value: "rrs-presentation.onrender.com,localhost,127.0.0.1"
      - key: ANCHOR_BROADCAST
        value: "False"

databases:
  - name: rrs_postgres
    engine: postgres
    version: "14"
    plan: free
